version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Backend/Dockerfile
    container_name: pietribiasi-backend
    restart: unless-stopped
    ports:
      # Mappa la porta INTERNA 8080 alla porta ESTERNA configurata dall'utente
      - "${BACKEND_PORT_EXTERN}:8080"
    environment:
      # Qui puoi passare altre configurazioni al backend, come la stringa di connessione
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION_STRING}
      - ASPNETCORE_URLS=http://+:8080

  frontend:
    build:
      context: ./Frontend/Web # Assicurati che il path sia corretto
      dockerfile: Dockerfile
    container_name: pietribiasi-frontend
    restart: unless-stopped
    ports:
      # Mappa la porta INTERNA 80 alla porta ESTERNA configurata dall'utente
      - "${FRONTEND_PORT_EXTERN}:80"
    depends_on:
      - backend

# NOTA: Le variabili come ${BACKEND_PORT_EXTERN} vengono lette da un file .env