// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using apiPB.Data;

#nullable disable

namespace apiPB.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250321112847_CreateVwWorkers")]
    partial class CreateVwWorkers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("apiPB.Models.MaStorage", b =>
                {
                    b.Property<string>("Storage")
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)");

                    b.Property<string>("Address")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .HasDefaultValue("");

                    b.Property<string>("Address2")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .HasDefaultValue("");

                    b.Property<string>("AllCompanies")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasDefaultValue("0")
                        .IsFixedLength();

                    b.Property<string>("City")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .HasDefaultValue("");

                    b.Property<int?>("CodeType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(3342336);

                    b.Property<int?>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(-1);

                    b.Property<string>("ConsignmentStock")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasDefaultValue("0")
                        .IsFixedLength();

                    b.Property<string>("Country")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .HasDefaultValue("");

                    b.Property<string>("County")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)")
                        .HasDefaultValue("");

                    b.Property<string>("CrossDocking")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasDefaultValue("0")
                        .IsFixedLength();

                    b.Property<string>("CrossDockingZone")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)")
                        .HasDefaultValue("");

                    b.Property<string>("Description")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)")
                        .HasDefaultValue("");

                    b.Property<string>("Disabled")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasDefaultValue("0")
                        .IsFixedLength();

                    b.Property<string>("District")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .HasDefaultValue("");

                    b.Property<string>("ExcludeFromOnHand")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasDefaultValue("0")
                        .IsFixedLength();

                    b.Property<string>("ExcludeFromValuation")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasDefaultValue("0")
                        .IsFixedLength();

                    b.Property<string>("Fax")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)")
                        .HasDefaultValue("");

                    b.Property<string>("FederalState")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)")
                        .HasDefaultValue("");

                    b.Property<string>("GoodsIssueZone")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("char(8)")
                        .HasDefaultValue("")
                        .IsFixedLength();

                    b.Property<string>("GoodsReceiptZone")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("char(8)")
                        .HasDefaultValue("")
                        .IsFixedLength();

                    b.Property<string>("GroupCode")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)")
                        .HasDefaultValue("");

                    b.Property<string>("InspectionZone")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)")
                        .HasDefaultValue("");

                    b.Property<int?>("InventoryScarcityCheckType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(25100288);

                    b.Property<int?>("InventoryShortageCheckType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(25100288);

                    b.Property<string>("IsMainStorage")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasDefaultValue("0")
                        .IsFixedLength();

                    b.Property<string>("IsocountryCode")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)")
                        .HasDefaultValue("")
                        .HasColumnName("ISOCountryCode");

                    b.Property<DateTime?>("LastSnapshotCertifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("('17991231')");

                    b.Property<string>("ManTwoStepsPutaway")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasDefaultValue("")
                        .IsFixedLength();

                    b.Property<string>("ManufacturingIssuePickZone")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)")
                        .HasDefaultValue("");

                    b.Property<string>("ManufacturingIssueZone")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)")
                        .HasDefaultValue("");

                    b.Property<string>("ManufacturingReceiptZone")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)")
                        .HasDefaultValue("");

                    b.Property<string>("Notes")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .HasDefaultValue("");

                    b.Property<string>("OwnedGoods")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasDefaultValue("0")
                        .IsFixedLength();

                    b.Property<short?>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)99);

                    b.Property<string>("ReturnZone")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("char(8)")
                        .HasDefaultValue("")
                        .IsFixedLength();

                    b.Property<int?>("SalesOrdersShortageCheckType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(25100288);

                    b.Property<int?>("SalesScarcityCheckType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(25100288);

                    b.Property<int?>("SalesShortageCheckType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(25100288);

                    b.Property<string>("ScrapZone")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)")
                        .HasDefaultValue("");

                    b.Property<string>("SearchZoneStrReplanish")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)")
                        .HasDefaultValue("");

                    b.Property<string>("SearchZoneStrategyPicking")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)")
                        .HasDefaultValue("");

                    b.Property<string>("SearchZoneStrategyPutaway")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)")
                        .HasDefaultValue("");

                    b.Property<int?>("SpecTypeReplenishment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(6750211);

                    b.Property<string>("SpecificatorReplenishment")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)")
                        .HasDefaultValue("");

                    b.Property<int?>("StockReturnStrategy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(26607618);

                    b.Property<string>("StorageBarcodePrefix")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)")
                        .HasDefaultValue("");

                    b.Property<string>("StorageReplenishment")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)")
                        .HasDefaultValue("");

                    b.Property<string>("StreetNo")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("");

                    b.Property<string>("StubBookAdjustment")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)")
                        .HasDefaultValue("");

                    b.Property<string>("StubBookInterStorageIn")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)")
                        .HasDefaultValue("")
                        .HasColumnName("StubBookInterStorageIN");

                    b.Property<string>("StubBookInterStorageOut")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)")
                        .HasDefaultValue("")
                        .HasColumnName("StubBookInterStorageOUT");

                    b.Property<string>("StubBookPurchases")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)")
                        .HasDefaultValue("");

                    b.Property<string>("StubBookSales")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)")
                        .HasDefaultValue("");

                    b.Property<string>("TaxJournalPurchases")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)")
                        .HasDefaultValue("");

                    b.Property<string>("TaxJournalSales")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)")
                        .HasDefaultValue("");

                    b.Property<DateTime>("Tbcreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("TBCreated")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("TbcreatedId")
                        .HasColumnType("int")
                        .HasColumnName("TBCreatedID");

                    b.Property<Guid?>("Tbguid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TBGuid")
                        .HasDefaultValueSql("(0x00)");

                    b.Property<DateTime>("Tbmodified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("TBModified")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("TbmodifiedId")
                        .HasColumnType("int")
                        .HasColumnName("TBModifiedID");

                    b.Property<string>("Telephone1")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("");

                    b.Property<string>("Telephone2")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("");

                    b.Property<string>("TwoStepsPutaway")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasDefaultValue("1")
                        .IsFixedLength();

                    b.Property<string>("UsedByMrp")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasDefaultValue("0")
                        .HasColumnName("UsedByMRP")
                        .IsFixedLength();

                    b.Property<string>("UsedByProduction")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasDefaultValue("0")
                        .IsFixedLength();

                    b.Property<string>("UsedForRetail")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasDefaultValue("0")
                        .IsFixedLength();

                    b.Property<int?>("WaptransferBetweenStorages")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(2032336896)
                        .HasColumnName("WAPTransferBetweenStorages");

                    b.Property<string>("Wms")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasDefaultValue("0")
                        .HasColumnName("WMS")
                        .IsFixedLength();

                    b.Property<DateTime?>("WmsactivationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("WMSActivationDate")
                        .HasDefaultValueSql("('17991231')");

                    b.Property<DateTime?>("WmsmanActivationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("WMSManActivationDate")
                        .HasDefaultValueSql("('17991231')");

                    b.Property<string>("WmsthirdParties")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasDefaultValue("0")
                        .HasColumnName("WMSThirdParties")
                        .IsFixedLength();

                    b.Property<string>("Zipcode")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("")
                        .HasColumnName("ZIPCode");

                    b.HasKey("Storage")
                        .HasName("PK_Storages");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Storage"), false);

                    b.HasIndex(new[] { "Description" }, "MA_Storages2");

                    b.ToTable("MA_Storages", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("apiPB.Models.RmWorker", b =>
                {
                    b.Property<int>("WorkerId")
                        .HasColumnType("int")
                        .HasColumnName("WorkerID");

                    b.Property<string>("Address2")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .HasDefaultValue("");

                    b.Property<string>("Bccemail")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .HasDefaultValue("")
                        .HasColumnName("BCCEmail");

                    b.Property<string>("Branch")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)")
                        .HasDefaultValue("");

                    b.Property<string>("Ccemail")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .HasDefaultValue("")
                        .HasColumnName("CCEmail");

                    b.Property<string>("Cgmmanager")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasDefaultValue("0")
                        .HasColumnName("CGMManager")
                        .IsFixedLength();

                    b.Property<string>("CgmviewAllData")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasDefaultValue("0")
                        .HasColumnName("CGMViewAllData")
                        .IsFixedLength();

                    b.Property<string>("CityOfBirth")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)")
                        .HasDefaultValue("");

                    b.Property<string>("CivilStatus")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)")
                        .HasDefaultValue("");

                    b.Property<string>("CompanyLogin")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)")
                        .HasDefaultValue("");

                    b.Property<string>("CostCenter")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)")
                        .HasDefaultValue("");

                    b.Property<DateTime?>("DateOfBirth")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("('17991231')");

                    b.Property<string>("Disabled")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasDefaultValue("0")
                        .IsFixedLength();

                    b.Property<string>("District")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .HasDefaultValue("");

                    b.Property<string>("DomicilyAddress")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)")
                        .HasDefaultValue("");

                    b.Property<string>("DomicilyCity")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .HasDefaultValue("");

                    b.Property<string>("DomicilyCountry")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .HasDefaultValue("");

                    b.Property<string>("DomicilyCounty")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)")
                        .HasDefaultValue("");

                    b.Property<string>("DomicilyFc")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("")
                        .HasColumnName("DomicilyFC");

                    b.Property<string>("DomicilyIsocode")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)")
                        .HasDefaultValue("")
                        .HasColumnName("DomicilyISOCode");

                    b.Property<string>("DomicilyZip")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("");

                    b.Property<string>("Email")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .HasDefaultValue("");

                    b.Property<DateTime?>("EmploymentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("('17991231')");

                    b.Property<string>("FederalState")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)")
                        .HasDefaultValue("");

                    b.Property<int?>("Gender")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(2097152);

                    b.Property<string>("HideOnLayout")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasDefaultValue("0")
                        .IsFixedLength();

                    b.Property<double?>("HourlyCost")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.Property<string>("ImagePath")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)")
                        .HasDefaultValue("");

                    b.Property<string>("IsRsenabled")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasDefaultValue("0")
                        .HasColumnName("IsRSEnabled")
                        .IsFixedLength();

                    b.Property<string>("LastName")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .HasDefaultValue("");

                    b.Property<string>("Latitude")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)")
                        .HasDefaultValue("");

                    b.Property<string>("Longitude")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)")
                        .HasDefaultValue("");

                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)")
                        .HasDefaultValue("");

                    b.Property<string>("Notes")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .HasDefaultValue("");

                    b.Property<string>("OmallowSetQuantity")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasDefaultValue("1")
                        .HasColumnName("OMAllowSetQuantity")
                        .IsFixedLength();

                    b.Property<int?>("OmprocessingType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(2051407874)
                        .HasColumnName("OMProcessingType");

                    b.Property<int?>("OmresourceDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(2051473414)
                        .HasColumnName("OMResourceDefault");

                    b.Property<string>("Password")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)")
                        .HasDefaultValue("");

                    b.Property<short?>("PasswordAttemptsNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0);

                    b.Property<string>("PasswordCannotChange")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasDefaultValue("0")
                        .IsFixedLength();

                    b.Property<DateTime?>("PasswordExpirationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("('17991231')");

                    b.Property<string>("PasswordMustBeChanged")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasDefaultValue("0")
                        .IsFixedLength();

                    b.Property<string>("PasswordNeverExpire")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasDefaultValue("1")
                        .IsFixedLength();

                    b.Property<string>("PasswordNotRenewable")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasDefaultValue("0")
                        .IsFixedLength();

                    b.Property<string>("Pin")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)")
                        .HasDefaultValue("")
                        .HasColumnName("PIN");

                    b.Property<string>("RegisterNumber")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)")
                        .HasDefaultValue("");

                    b.Property<DateTime?>("ResignationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("('17991231')");

                    b.Property<string>("SenderEmail")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .HasDefaultValue("");

                    b.Property<string>("SkypeId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .HasDefaultValue("")
                        .HasColumnName("SkypeID");

                    b.Property<double?>("SpendingLimit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValueSql("('')");

                    b.Property<string>("StreetNo")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("");

                    b.Property<DateTime>("Tbcreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("TBCreated")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("TbcreatedId")
                        .HasColumnType("int")
                        .HasColumnName("TBCreatedID");

                    b.Property<Guid>("Tbguid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TBGuid")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("Tbmodified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("TBModified")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("TbmodifiedId")
                        .HasColumnType("int")
                        .HasColumnName("TBModifiedID");

                    b.Property<string>("Telephone1")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("");

                    b.Property<string>("Telephone2")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("");

                    b.Property<string>("Telephone3")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("");

                    b.Property<string>("Telephone4")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("");

                    b.Property<string>("Title")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)")
                        .HasDefaultValue("");

                    b.Property<string>("Url")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .HasDefaultValue("")
                        .HasColumnName("URL");

                    b.HasKey("WorkerId");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("WorkerId"), false);

                    b.HasIndex(new[] { "CompanyLogin", "WorkerId" }, "IX_RM_Workers_1");

                    b.ToTable("RM_Workers", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("apiPB.Models.RmWorkersField", b =>
                {
                    b.Property<int>("WorkerId")
                        .HasColumnType("int")
                        .HasColumnName("WorkerID");

                    b.Property<short>("Line")
                        .HasColumnType("smallint");

                    b.Property<string>("FieldName")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .HasDefaultValue("");

                    b.Property<string>("FieldValue")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("varchar(256)")
                        .HasDefaultValue("");

                    b.Property<string>("HideOnLayout")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasDefaultValue("")
                        .IsFixedLength();

                    b.Property<string>("Notes")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .HasDefaultValue("");

                    b.Property<DateTime>("Tbcreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("TBCreated")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("TbcreatedId")
                        .HasColumnType("int")
                        .HasColumnName("TBCreatedID");

                    b.Property<DateTime>("Tbmodified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("TBModified")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("TbmodifiedId")
                        .HasColumnType("int")
                        .HasColumnName("TBModifiedID");

                    b.HasKey("WorkerId", "Line");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("WorkerId", "Line"), false);

                    b.ToTable("RM_WorkersFields", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("apiPB.Models.VwWorkers", b =>
                {
                    b.Property<int>("WorkerId")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LastLogin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Storage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StorageVersamenti")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoUtente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WorkerId", "Password");

                    b.ToTable("VwWorkers");
                });

            modelBuilder.Entity("apiPB.Models.RmWorkersField", b =>
                {
                    b.HasOne("apiPB.Models.RmWorker", "Worker")
                        .WithMany("RmWorkersFields")
                        .HasForeignKey("WorkerId")
                        .IsRequired()
                        .HasConstraintName("FK_RM_WorkersFields_00");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("apiPB.Models.RmWorker", b =>
                {
                    b.Navigation("RmWorkersFields");
                });
#pragma warning restore 612, 618
        }
    }
}
