name: Build App on Develop Push

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: pip install pywebview

      - name: Run configure and build script
        run: |
          cd Scripts
          python build_script.py --mode full
          python build_script_FE_only.py --mode full
        shell: bash
