name: Build Python to EXE
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
      - name: Build EXE
        run: |
          pyinstaller --onefile --noconsole BuildScripts/build.py
      - name: Move EXE to root and cleanup
        run: |
          Move-Item -Path "dist\build.exe" -Destination "build.exe"
          Remove-Item -Path "dist" -Recurse -Force -ErrorAction SilentlyContinue
          Remove-Item -Path "build" -Recurse -Force -ErrorAction SilentlyContinue
          Remove-Item -Path "build.spec" -Force -ErrorAction SilentlyContinue
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: config-generator
          path: build.exe