name: Build Python to EXE

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'BuildScripts/**'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'BuildScripts/**'

  workflow_dispatch:

permissions:
  contents: write
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0'

      - name: Cleanup previous distribution directory
        run: |
          Remove-Item -Path "${{ github.workspace }}/BuildAndDistr" -Recurse -Force -ErrorAction SilentlyContinue

      - name: Setup Distribution Direcotry
        run: |
          New-Item -ItemType Directory -Path "${{ github.workspace }}/BuildAndDistr" -Force
          New-Item -ItemType Directory -Path "${{ github.workspace }}/BuildAndDistr/PietribiasiApp" -Force
          New-Item -ItemType Directory -Path "${{ github.workspace }}/BuildAndDistr/PietribiasiApp_distribution" -Force

      - name: Publish ASP.NET Core Backend
        run: |
          dotnet publish ./apiPB/apiPB.csproj --configuration Release --output ${{github.workspace}}/BuildAndDistr/PietribiasiApp/App --runtime win-x64 --self-contained true /p:UseAppHost=true
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
      
      - name: Build EXE
        run: |
          cd BuildScripts
          pyinstaller --onefile --add-data "script_utils.py;." --add-data "build.json;." build.py
      
      - name: Move EXE to root and cleanup
        run: |
          Remove-Item -Path "build.exe" -Force -ErrorAction SilentlyContinue
          Move-Item -Path "BuildScripts\dist\build.exe" -Destination "build.exe"
          Remove-Item -Path "BuildScripts\dist" -Recurse -Force -ErrorAction SilentlyContinue
          Remove-Item -Path "BuildScripts\build" -Recurse -Force -ErrorAction SilentlyContinue
          Remove-Item -Path "BuildScripts\build.spec" -Force -ErrorAction SilentlyContinue
      
      - name: Commit and push executable
        run: |
          git config --local user.email "raul.pianon@studenti.unipd.it"
          git config --local user.name "RaulPianon"
          # Configura un utente fittizio per il commit o da un utente specifico
          # git config --local user.email "action@github.com"
          # git config --local user.name "GitHub Action"
            git add build.exe 
            git add BuildAndDistr
          git commit -m "Auto-build: Updated Distribution" || exit 0
          git push
      
      # - name: Upload artifact (backup)
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: config-generator
      #     path: BuildAndDistr 